### ISSUE TITLE
[Bug] Doris-flinks-connector does not support parquet format?

### ISSUE THREAD

**Issue by MOBIN-F** [apache/doris-flink-connector#278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

flink-doris-connector-1.17-1.4.0

### What's Wrong?

```
CREATE TABLE doris_sink(
   ......
) WITH (
      'connector' = 'doris',
      'fenodes' = 'xxxx',
      'table.identifier' = 'xx.xxxx',
      'username' = 'xx',
      'password' = 'xx',
      'sink.properties.format' = 'parquet'
);
```
The following error occurs when ’sink.properties.format' = 'parquet' is set

```
Caused by: java.lang.IllegalStateException: null
	at org.apache.flink.util.Preconditions.checkState(Preconditions.java:177)
	at org.apache.doris.flink.sink.writer.RowDataSerializer$Builder.build(RowDataSerializer.java:155)
	at org.apache.doris.flink.table.DorisDynamicTableSink.getSinkRuntimeProvider(DorisDynamicTableSink.java:104)
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecSink.createSinkTransformation(CommonExecSink.java:151)
	at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:214)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:167)
	at org.apache.flink.table.planner.delegation.StreamPlanner.$anonfun$translateToPlan$1(StreamPlanner.scala:85)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
```

There is no paruqet type
![image](https://github.com/apache/doris-flink-connector/assets/11769953/4361905d-ecd2-4f8c-9246-e5c6d939be89)

### What You Expected?

support parquet format

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DongLiang-0** [comment]
Doris flink connector internally uses stream load to import into doris. Stream load currently only supports csv and json formats.

**Comment by JNSimba** [comment]
The latest master supports writing in arrow format, which may be helpful to you.
