### ISSUE TITLE
[Bug] DorisSource createEnumerator error when has fiter condition(pushDown)

### ISSUE THREAD

**Issue by yingh0ng** [apache/doris-flink-connector#376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.6.0

### What's Wrong?

my sql exsit filter query but column name is "null". 
Here is the detailed log:

2024-05-06 09:45:01.836 [flink-akka.actor.default-dispatcher-8970] INFO  org.apache.doris.flink.source.DorisSource - Query SQL Sending to Doris FE is: 'select `FINISHEDFLAG_`, `FIELD0006_`, `FIELD0031_`, `FIELD0030_` from `qixi_ods`.`ods_dcb850f793dd87c6ae90e3aa81875608` where (null = 4)'.
2024-05-06 09:45:01.836 [flink-akka.actor.default-dispatcher-8970] INFO  org.apache.doris.flink.source.DorisSource - Send request to Doris FE 'http://192.168.9.200:8030/api/qixi_ods/ods_dcb850f793dd87c6ae90e3aa81875608/_query_plan' with user 'root'.
2024-05-06 09:45:01.843 [flink-akka.actor.default-dispatcher-8970] ERROR org.apache.doris.flink.source.DorisSource - Doris FE's response cannot map to schema. res: {"exception":"PlannershouldplanjustonlyoneScanNodebutfound[0]","status":500}

Caused by: org.apache.doris.flink.exception.DorisException: Doris FE's response cannot map to schema. res: {"exception":"PlannershouldplanjustonlyoneScanNodebutfound[0]","status":500}
        at org.apache.doris.flink.rest.RestService.getQueryPlan(RestService.java:653)
        at org.apache.doris.flink.rest.RestService.findPartitions(RestService.java:620)
        at org.apache.doris.flink.source.DorisSource.createEnumerator(DorisSource.java:97)
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:222)

### What You Expected?

no error. BTW how to disable the pushdown?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yingh0ng** [comment]
How to Reproduce?
I used a founction column in where condition, like: 
select a, b, c
from (select a, b, (a+b) as c from tablea)tableb
where c=4;

**Comment by Tyxuani** [comment]
My flink env contains hadoop dependecies, and will arise this issue: 

Caused by: org.apache.doris.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "exception" (class org.apache.doris.flink.rest.models.QueryPlan), not marked as ignorable (3 known properties: "partitions", "status", "opaqued_query_plan"])
 at [Source: (String)"{"exception":"PlannershouldplanjustonlyoneScanNodebutfound[0]","status":500}"; line: 1, column: 15] (through reference chain: org.apache.doris.flink.rest.models.QueryPlan["exception"])
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at org.apache.doris.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at org.apache.doris.flink.rest.RestService.getQueryPlan(RestService.java:645)

**Comment by Tyxuani** [comment]
Resolved this by myself: `tinyint` `is_aa` can't use to condition `is_aa = 1` , need to define as `int`.

**Comment by vinlee19** [comment]
@yingh0ng @Tyxuani We can communicate on WeChat. Here's my WeChat ID: xyelonx
