### ISSUE TITLE
[Bug] NullPointerException in SourceReaderBase

### ISSUE THREAD

**Issue by yingh0ng** [apache/doris-flink-connector#387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

connectro 1.6.0

### What's Wrong?

`Caused by: java.lang.NullPointerException    
at org.apache.flink.connector.base.source.reader.SourceReaderBase.finishCurrentFetch(SourceReaderBase.java:194)    
at org.apache.flink.connector.base.source.reader.SourceReaderBase.moveToNextSplit(SourceReaderBase.java:208)    
at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:173)    
at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:131)    
at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:419)    
at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)    
at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)    
at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:550)    
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)    
at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:839)    
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:788)    
at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)    
at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:931)    
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)    
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)    
at java.lang.Thread.run(Thread.java:748) `

### What You Expected?

no error

### env
flink-1.17.2, use local mode and running on k8s
doris 2.1 (one fe, one be)

### operation
1. Used doris-flink-connector to read a Doris table.
2. Used doris-flink-connector to write the table to Doris.

### Anything Else?

After i add the config "doris.request.tablet.size=20" to the table source, everything works well.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Repeat with 411, close
