### ISSUE TITLE
[Bug] Data Visible in Flink UI but Not Reaching Downstream Database

### ISSUE THREAD

**Issue by HeyChiang** [apache/doris-flink-connector#442]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

flink-1.19.1
flink-doris-connector-1.19-1.6.2.jar
flink-cdc-common-3.0.1.jar
flink-sql-connector-mysql-cdc-3.0.1.jar
flink-sql-connector-oracle-cdc-3.0.1.jar

### What's Wrong?

![QQ_1721803834101](https://github.com/user-attachments/assets/b9a2a4a1-6e50-4ed3-9109-181e4d299e66)

I'm observing a discrepancy between the data shown in the Flink UI and what's actually being written to the downstream database. The Flink UI shows a significant amount of data being processed and sent (as indicated by the colored blocks representing different tasks), but when I check the downstream database, no records are present. This suggests that while data is being read from the source and processed within Flink, it's not successfully being written to the target database.

### What You Expected?

I expected that the data shown as processed in the Flink UI would correspond to actual records written to the downstream database. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HeyChiang** [comment]
![QQ_1721804529446](https://github.com/user-attachments/assets/8ffeb9da-07b9-4b87-8d3a-086e1f2d1865)
`
"Process -> (BMS_BATCH_DEF: Writer -> BMS_BATCH_DEF: Committer, BMS_LOT_DEF: Writer -> BMS_LOT_DEF: Committer, BMS_STORER_POS: Writer -> BMS_STORER_POS: Committer, BMS_ST_IO_DOC: Writer -> BMS_ST_IO_DOC: Committer, BMS_ST_IO_DTL: Writer -> BMS_ST_IO_DTL: Committer, BMS_SU_SET_DOC: Writer -> BMS_SU_SET_DOC: Committer, BMS_SU_SET_DTL: Writer -> BMS_SU_SET_DTL: Committer, GPCS_INSIDER: Writer -> GPCS_INSIDER: Committer, GPCS_PLACEPOINT: Writer -> GPCS_PLACEPOINT: Committer, GPCS_PLACEPOINT_CLASS: Writer -> GPCS_PLACEPOINT_CLASS: Committer, GPCS_PLACEPOINT_CLASS_DTL: Writer -> GPCS_PLACEPOINT_CLASS_DTL: Committer, GRESA_SA_DOC: Writer -> GRESA_SA_DOC: Committer, GRESA_SA_DTL: Writer -> GRESA_SA_DTL: Committer, NGPCS_ALL_PRICE: Writer -> NGPCS_ALL_PRICE: Committer, NP_EFILES_OP_FILE: Writer -> NP_EFILES_OP_FILE: Committer, PUB_BRAND: Writer -> PUB_BRAND: Committer, PUB_EMPLOYEE: Writer -> PUB_EMPLOYEE: Committer, PUB_FACTORY: Writer -> PUB_FACTORY: Committer, PUB_GOODS: Writer -> PUB_GOODS: Committer, PUB_GOODS_CLASS: Writer -> PUB_GOODS_CLASS: Committer, PUB_GOODS_CLASS_DTL: Writer -> PUB_GOODS_CLASS_DTL: Committer) (2/3)#0" Id=12810 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@24273330
	at java.base@11.0.22/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@24273330
	at java.base@11.0.22/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.22/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.base@11.0.22/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
	at org.apache.doris.flink.sink.writer.RecordBuffer.write(RecordBuffer.java:93)
	at org.apache.doris.flink.sink.writer.RecordStream.write(RecordStream.java:63)
	at org.apache.doris.flink.sink.writer.DorisStreamLoad.writeRecord(DorisStreamLoad.java:251)
	at org.apache.doris.flink.sink.writer.DorisWriter.writeOneDorisRecord(DorisWriter.java:216)
	at org.apache.doris.flink.sink.writer.DorisWriter.write(DorisWriter.java:186)
	at app//org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.processElement(SinkWriterOperator.java:160)
	at app//org.apache.flink.streaming.runtime.io.RecordProcessorUtils$$Lambda$825/0x00000008007eec40.accept(Unknown Source)
	at app//org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:75)
	at app//org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:61)
	at app//org.apache.flink.streaming.runtime.tasks.ChainingOutput.collectAndCheckIfChained(ChainingOutput.java:96)
	at app//org.apache.flink.streaming.runtime.tasks.BroadcastingOutputCollector.collect(BroadcastingOutputCollector.java:94)
	at app//org.apache.flink.streaming.api.operators.ProcessOperator$ContextImpl.output(ProcessOperator.java:103)
	at org.apache.doris.flink.tools.cdc.ParsingProcessFunction.processElement(ParsingProcessFunction.java:51)
	at org.apache.doris.flink.tools.cdc.ParsingProcessFunction.processElement(ParsingProcessFunction.java:31)
	at app//org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)
	at app//org.apache.flink.streaming.runtime.io.RecordProcessorUtils$$Lambda$825/0x00000008007eec40.accept(Unknown Source)
	at app//org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:238)
	at app//org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:157)
	at app//org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:114)
	at app//org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at app//org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:579)
	at app//org.apache.flink.streaming.runtime.tasks.StreamTask$$Lambda$746/0x00000008006ff440.runDefaultAction(Unknown Source)
	at app//org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at app//org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:909)
	at app//org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:858)
	at app//org.apache.flink.runtime.taskmanager.Task$$Lambda$1135/0x0000000800928c40.run(Unknown Source)
	at app//org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at app//org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937)
	at app//org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751)
	at app//org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.base@11.0.22/java.lang.Thread.run(Thread.java:834)
`

**Comment by JasonLeeCoding** [comment]
Is checkpoint enabled for the flink job?

**Comment by HeyChiang** [comment]
> Is checkpoint enabled for the flink job?

Yes. Here is the Flink command I'm using：

```bash
bin/flink run \
     -Dexecution.checkpointing.interval=2min \
     -Dexecution.checkpointing.timeout=60min \
     -Dexecution.checkpointing.tolerable-failed-checkpoints=3 \
     -Dparallelism.default=3 \
     -c org.apache.doris.flink.tools.cdc.CdcTools \
     lib/flink-doris-connector-1.19-1.6.2.jar \
     oracle-sync-database \
     --database djwkerp \
     --oracle-conf hostname=192.168.191.210 \
     --oracle-conf port=1521 \
     --oracle-conf username=cdc_sync_user \
     --oracle-conf password="xxxxxxxxxx" \
     --oracle-conf database-name=data \
     --oracle-conf schema-name=DJWKERP \
     --including-tables "NGPCS_ALL_PRICE|GPCS_PLACEPOINT|PUB_EMPLOYEE|BMS_BATCH_DEF|BMS_LOT_DEF|BMS_STORER_POS|GRESA_SA_DOC|GRESA_SA_DTL|GPCS_INSIDER|BMS_ST_IO_DOC|BMS_ST_IO_DTL|GPCS_PLACEPOINT_CLASS|GPCS_PLACEPOINT_CLASS_DTL|PUB_GOODS_CLASS|PUB_GOODS_CLASS_DTL|BMS_SU_SET_DOC|BMS_SU_SET_DTL|PUB_GOODS|PUB_FACTORY|PUB_BRAND|NP_EFILES_OP_FILE" \
     --sink-conf fenodes=192.168.191.93:8030 \
     --sink-conf username=cdc_sync_user \
     --sink-conf password="xxxxxxxxxx" \
     --sink-conf jdbc-url=jdbc:mysql://192.168.191.93:9030?allowPublicKeyRetrieval=true \
     --sink-conf sink.label-prefix=label \
     --table-conf replication_num=3
```

**Comment by JasonLeeCoding** [comment]
Have checkpoints been completed successfully?

**Comment by HeyChiang** [comment]
![QQ_1721806383826](https://github.com/user-attachments/assets/a961bf25-e16c-477a-b485-186e9fac3be2)
FAILED

**Comment by JNSimba** [comment]
During full synchronization, Oracle will not start writing until it has completed pulling the existing data. You can try increasing these parameters https://nightlies.apache.org/flink/flink-cdc-docs-release-3.1/docs/connectors/flink-sources/oracle-cdc/#cant-perform-checkpoint-during-scanning-snapshot-of-tables

**Comment by HeyChiang** [comment]
thanks, bro @JNSimba
